---
# handlers file for cri-o
- name: reload systemd
  systemd:
    daemon_reload: yes 

- name: enable crio
  systemd:
    name: crio 
    enabled: yes
    daemon_reload: yes

- name: start crio
  systemd:
    name: crio 
    state: started
    daemon_reload: yes 

- name: reload crio
  systemd:
    name: crio
    state: reloaded
    daemon_reload: yes 

- name: restart crio
  systemd:
    name: crio
    state: restarted
    daemon_reload: yes 
