---
# tasks file for cri-o on Rocky Linux, Redhat or CentOS

- name: Create system network configuration file {{ crio_net_configfile }}
  file:
    path: "{{ crio_net_configfile }}"
    state: touch
    mode: 0640

- name: Set system network configuration
  blockinfile:
    path: "{{ crio_net_configfile }}"
    block: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  command: sysctl --system

- name: "Add apt signing keys"
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "{{ ubuntu_crio_gpgkey1 }}"
    - "{{ ubuntu_crio_gpgkey2 }}"

- name: Add containers libraries repository
  apt_repository:
    repo: "{{ ubuntu_crio_repourl1 }}"
    filename: "{{ ubuntu_crio_repofilename1 }}"
    mode: 0640
    state: present
    update_cache: yes

- name: Add CRI-O {{ crio_version }} repository
  apt_repository:
    repo: "{{ ubuntu_crio_repourl2 }}"
    filename: "{{ ubuntu_crio_repofilename2 }}"
    mode: 0640
    state: present
    update_cache: yes

# Installation of CRI-O 
- name: "Install CRI-O {{ crio_version }} packages: {{ ubuntu_crio_pkgname }}, {{ ubuntu_criotools_pkgname }}, {{ ubuntu_criorunc_pkgname }}"
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    autoremove: yes
  loop:
    - "{{ ubuntu_crio_pkgname }}"
    - "{{ ubuntu_criotools_pkgname }}"
    - "{{ ubuntu_criorunc_pkgname }}"
  notify:
    - enable crio

# Upload registries configuration file
- name: "Upload registries configuration file"  
  template:
    src:   registries.conf.j2
    dest:   "{{ crio_registries_configfile }}"
    owner: root
    group: root
    mode:  0640
    backup: yes

# Upload CRI-O configuration file
- name: "Upload CRI-O configuration file {{ crio_crio_configfile }}"  
  template:
    src:   crio.conf.j2
    dest:   "{{ crio_crio_configfile }}"
    owner: root
    group: root
    mode:  0640
    backup: yes

# Upload CRI-O bridge configuration file
- name: "Upload CRI-O bridge configuration file {{ crio_bridge_configfile }}"  
  template:
    src: 100-crio-bridge.conf.j2
    dest: "{{ crio_bridge_configfile }}"
    owner: root
    group: root
    mode: 0640
    backup: yes

- name: "Restart CRI-O" 
  systemd:
    name: crio
    state: restarted
    enabled: yes
    daemon_reload: yes
