---
# vars file for auditing 
#
######################################################
# Common variables
#
audit_apiserver_policydir: /etc/kubernetes/policies
audit_apiserver_policyfile: "{{ audit_apiserver_policydir }}/B13_K8S_Audit-Policy_simple.yaml"
audit_apiserver_logdir: /var/log/apiserver
audit_apiserver_logfile: "{{ audit_apiserver_logdir }}/audit.log"
k8s_apiserver_manifest: /etc/kubernetes/manifests/kube-apiserver.yaml
# apiserver command line arguments for auditing
#audit_apiserver_args: |2
#          - --audit-policy-file={{ audit_apiserver_policyfile }}
#          - --audit-log-path={{ audit_apiserver_logfile }}
#          - --audit-log-maxage=1
#          - --audit-log-maxsize=20
#          - --audit-log-maxbackup=5
#          - --feature-gates=AdvancedAuditing=false
## apiserver volumes mount point definitions for audit log files and policies
#audit_apiserver_volumeMounts: |2
#          - mountPath: {{ audit_apiserver_policyfile }}
#            name: b13-audit-policy
#            readOnly: true
#          - mountPath: {{ audit_apiserver_logfile }}
#            name: b13-audit-log
#            readOnly: false
## apiserver volumes definitions for audit log files and policies
#audit_apiserver_volumes: |2
#      - hostPath:
#          path: {{ audit_apiserver_policyfile }}
#          type: File
#        name: b13-audit-policy
#      - hostPath:
#          path: {{ audit_apiserver_logfile }}
#          type: FileOrCreate
#        name: b13-audit-log
#
# End of common varibles
######################################################
######################################################
# Rocky Linux (CentOS) specific
#

#
# End of CentOS specific
######################################################

######################################################
# Ubuntu specific
#

#
# End of Ubuntu specific
######################################################

