---
# tasks file for k8s CNI

- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_facts
  when: cni_display_facts == "yes"

- name: Deploy Calico CNI on Ubuntu
  become: no
  #shell: kubectl apply -f {{ ubuntu_calico_url }} 
  #command: kubectl --kubeconfig=~{{ remote_user }}/.kube/config apply -f {{ ubuntu_calico_url }} 
  command: kubectl apply -f {{ ubuntu_calico_url }} 
  when: (inventory_hostname in groups['k8smasternodes']) and (ubuntu_cni == "calico")

- name: Deploy Weave CNI on Ubuntu
  become: no
  shell: kubectl apply -f {{ ubuntu_weave_url }} 
  #command: kubectl --kubeconfig=~{{ remote_user }}/.kube/config apply -f {{ ubuntu_weave_url }} 
  #command: kubectl apply -f {{ ubuntu_weave_url }} 
  when: (inventory_hostname in groups['k8smasternodes']) and (ubuntu_cni == "weave")
