---
# vars file for k8s CNI
#
######################################################
# Common variables
#
# If one wants to display the ansible facts while running the playbook, set the following variable to "yes"
cni_display_facts: "no"
# Kubernetes pods subnet
# Ensure there is no overlap with enterprise subnets so that there is no routing ambiguity in the pods
k8s_pods_subnet: "10.100.0.0/16"
k8s_pods_subnetmask: "24"
cilium_helm_repository: "https://helm.cilium.io/"
cilium_helm_chart: "cilium/cilium"
cilium_version: "1.11.4"
cilium_activate_hubble: "no"
#
# End of common varibles
######################################################
######################################################
# CentOS specific
# CNI to be used
#centos_cni: antrea
centos_cni: calico
#centos_cni: cilium
#centos_cni: weave
# URL for CNI
centos_antrea_url: "https://raw.githubusercontent.com/antrea-io/antrea/main/build/yamls/antrea.yml"
centos_calico_url: "https://projectcalico.docs.tigera.io/manifests/calico.yaml"
centos_weave_url: "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
centos_host_interface: enp0s3
#
# End of CentOS specific
######################################################

######################################################
# Ubuntu specific
#
# CNI to be used
#ubuntu_cni: antrea
ubuntu_cni: calico
#ubuntu_cni: cilium
#ubuntu_cni: weave
# URL for CNI
ubuntu_antrea_url: "https://raw.githubusercontent.com/antrea-io/antrea/main/build/yamls/antrea.yml"
#ubuntu_calico_url: "https://docs.projectcalico.org/manifests/calico.yaml"
#ubuntu_calico_url: "https://projectcalico.docs.tigera.io/manifests/calico.yaml"
#ubuntu_calico_url: "https://docs.projectcalico.org/manifests/calico-typha.yaml"
#ubuntu_calico_url: "https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml"
#ubuntu_calico_url2: "https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml"
#ubuntu_calico_ippoolsfile: "calico_IPPools.yaml"
ubuntu_calico_url: "https://projectcalico.docs.tigera.io/manifests/calico.yaml"
ubuntu_weave_url: "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
#
# End of Ubuntu specific
######################################################

