---
# vars file for cri-o on Ubuntu/Debian or Rocky-Linux/Centos/Redhat 
#
######################################################
# Common variables
#
# CRI-O version to be installed.
# Ensure this is the same version than the one of Kubernetes
# Available version of Kubernetes and cri-o can be found using :
# curl -s https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages | grep Version | awk '{print $2}'
# https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:
k8s_version: "1.23"
crio_version: "{{ k8s_version }}"
# CRI-O pods subnet
# Ensure chosen subnet doesn't conflict with enterprise subnet that pods should connect to.
crio_pods_subnet: "10.100.0.0/16"
# Allowed OCI images registries
# Add or remove required registries
crio_allowed_registries: "'docker.io', 'registry.fedoraproject.org', 'registry.access.redhat.com'"
# System network configuration file
crio_net_configfile: "/etc/sysctl.d/99-kubernetes-cri.conf"
# Registries configuration file
crio_registries_configfile: "/etc/containers/registries.conf"
# CRI-O configuration file
crio_crio_configfile: "/etc/crio/crio.conf"
# CRI-O bridge configuration file
crio_bridge_configfile: "/etc/cni/net.d/100-crio-bridge.conf"
#
# End of common varibles
######################################################
######################################################
# Rocky Linux (CentOS) specific
#
#centos_crio_version: "CentOS_8_Stream"
centos_crio_version: "CentOS_8"
#
# CentOS containers libraries repository
# See content of https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{centos_crio_version}}/devel:kubic:libcontainers:stable.repo
centos_crio_reponame1: "devel_kubic_libcontainers_stable"
centos_crio_repobaseurl1: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{centos_crio_version}}/"
centos_crio_repogpgkey1: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{centos_crio_version}}/repodata/repomd.xml.key"
centos_crio_repodesc1: "Stable Releases of Upstream github.com/containers packages ({{centos_crio_version}})"
#
# CRI-O repository for CentOS
# See content of https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}/{{centos_crio_version}}/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}.repo
centos_crio_reponame2: "devel_kubic_libcontainers_stable_cri-o_{{crio_version}}"
centos_crio_repobaseurl2: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{crio_version}}/{{centos_crio_version}}/"
centos_crio_repogpgkey2: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{crio_version}}/{{centos_crio_version}}/repodata/repomd.xml.key"
centos_crio_repodesc2: "devel:kubic:libcontainers:stable:cri-o:{{crio_version}} ({{centos_crio_version}})"
#centos_crio_pkgname: "cri-o-{{crio_version}}"
centos_crio_pkgname: "cri-o"
centos_criotools_pkgname: "cri-tools"
#
# End of CentOS specific
######################################################

######################################################
# Ubuntu specific
#
ubuntu_crio_version: "xUbuntu_20.04"
# Ubuntu containers libraries repository
ubuntu_crio_repourl1: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ubuntu_crio_version}}/ /"
ubuntu_crio_gpgkey1: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ubuntu_crio_version}}/Release.key"
ubuntu_crio_repofilename1: "devel:kubic:libcontainers:stable"
# CRI-O repository for Ubuntu
ubuntu_crio_repourl2: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{crio_version}}/{{ubuntu_crio_version}}/ /"
ubuntu_crio_gpgkey2: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{crio_version}}/{{ubuntu_crio_version}}/Release.key"
ubuntu_crio_repofilename2: "devel:kubic:libcontainers:stable:cri-o:{{crio_version}}"
#crio_crio_pkgname: "cri-o-{{crio_version}}"
ubuntu_crio_pkgname: "cri-o"
ubuntu_criorunc_pkgname: "cri-o-runc"
ubuntu_criotools_pkgname: "cri-tools"
#
# End of Ubuntu specific
######################################################

